// Generated by gencpp from file adbot_msgs/SprMsg.msg
// DO NOT EDIT!


#ifndef ADBOT_MSGS_MESSAGE_SPRMSG_H
#define ADBOT_MSGS_MESSAGE_SPRMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace adbot_msgs
{
template <class ContainerAllocator>
struct SprMsg_
{
  typedef SprMsg_<ContainerAllocator> Type;

  SprMsg_()
    : isOn(false)  {
    }
  SprMsg_(const ContainerAllocator& _alloc)
    : isOn(false)  {
  (void)_alloc;
    }



   typedef uint8_t _isOn_type;
  _isOn_type isOn;





  typedef boost::shared_ptr< ::adbot_msgs::SprMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::adbot_msgs::SprMsg_<ContainerAllocator> const> ConstPtr;

}; // struct SprMsg_

typedef ::adbot_msgs::SprMsg_<std::allocator<void> > SprMsg;

typedef boost::shared_ptr< ::adbot_msgs::SprMsg > SprMsgPtr;
typedef boost::shared_ptr< ::adbot_msgs::SprMsg const> SprMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::adbot_msgs::SprMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::adbot_msgs::SprMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::adbot_msgs::SprMsg_<ContainerAllocator1> & lhs, const ::adbot_msgs::SprMsg_<ContainerAllocator2> & rhs)
{
  return lhs.isOn == rhs.isOn;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::adbot_msgs::SprMsg_<ContainerAllocator1> & lhs, const ::adbot_msgs::SprMsg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace adbot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::adbot_msgs::SprMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::adbot_msgs::SprMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::adbot_msgs::SprMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::adbot_msgs::SprMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::adbot_msgs::SprMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::adbot_msgs::SprMsg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::adbot_msgs::SprMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7815df4e3625e249c3731540caef0458";
  }

  static const char* value(const ::adbot_msgs::SprMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7815df4e3625e249ULL;
  static const uint64_t static_value2 = 0xc3731540caef0458ULL;
};

template<class ContainerAllocator>
struct DataType< ::adbot_msgs::SprMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "adbot_msgs/SprMsg";
  }

  static const char* value(const ::adbot_msgs::SprMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::adbot_msgs::SprMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool isOn\n"
;
  }

  static const char* value(const ::adbot_msgs::SprMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::adbot_msgs::SprMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.isOn);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SprMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::adbot_msgs::SprMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::adbot_msgs::SprMsg_<ContainerAllocator>& v)
  {
    s << indent << "isOn: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.isOn);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ADBOT_MSGS_MESSAGE_SPRMSG_H
